import { ASSET_PATHS, PROGRAM_FALLBACK_GRADIENTS } from "@/lib/siteConfig";
import type { Program } from "@/lib/types";

export const programs: Program[] = [
  {
    id: "program-001",
    title: "레이저 서바이벌",
    slug: "laser-survival",
    shortDescription:
      "투사체 없는 적외선 장비를 활용해 팀워크와 전략을 경험하는 안전한 액티브 체험학습",
    description:
      "적외선 장비 기반 팀 미션으로 구성되는 활동형 프로그램입니다. 학생들이 역할을 나누고 전략을 세우며, 협동의 가치를 자연스럽게 익히도록 설계했습니다.",
    category: "activity",
    icon: "laser-survival",
    iconKey: "laser-survival",
    tags: ["활동형", "팀빌딩", "전략", "협동", "초등추천"],
    targetAudience: "초등 3~6학년, 중학생, 청소년기관",
    targetGrades: ["초등 3~6학년", "중학생", "청소년기관"],
    duration: "1~2교시 기본 운영 (확장 운영 가능)",
    locationType: "학교 운동장, 강당, 실내 체육관",
    recommendedFor: [
      "학급 단합 활동이 필요한 학교",
      "체험학습 주간 특별 프로그램을 찾는 기관",
      "학생 주도형 팀미션 수업을 원하는 담당자",
    ],
    requirements: [
      "팀 활동이 가능한 넓은 공간",
      "편한 복장과 운동화",
      "사전 안전 안내 시간 10~15분",
    ],
    processSteps: [
      "장비 소개와 안전 수칙 안내",
      "팀 구성 및 역할 배정",
      "전략 미션 라운드 진행",
      "라운드 피드백 및 협동 포인트 정리",
      "정리 활동 및 마무리",
    ],
    safetyNotes: [
      "투사체가 없는 적외선 장비로 진행합니다.",
      "현장 동선 구역을 사전에 지정해 운영합니다.",
      "학생 눈높이에 맞춘 규칙 설명으로 안전한 참여를 유도합니다.",
    ],
    expectedEffects: [
      "팀워크와 의사소통 능력 향상",
      "규칙 기반 활동에서의 책임감 강화",
      "활동 후 자기 성찰과 협업 경험 확장",
    ],
    basePrice: 10000,
    priceNote: "운영 형태와 인원에 따라 견적 안내",
    imageUrl: ASSET_PATHS.programs["laser-survival"],
    imageAlt: "레이저 서바이벌 체험 중인 학생들",
    fallbackGradient: PROGRAM_FALLBACK_GRADIENTS["laser-survival"],
    isPublished: true,
    sortOrder: 1,
  },
  {
    id: "program-002",
    title: "하늘그네",
    slug: "sky-swing",
    shortDescription:
      "하늘을 나는 듯한 경험을 통해 도전과 성취감을 느끼는 모험형 체험 프로그램",
    description:
      "학생들이 도전과 성취를 체감할 수 있도록 설계된 모험형 프로그램입니다. 난이도 조절형 운영으로 참여 부담을 낮추고 자신감 성장을 돕습니다.",
    category: "adventure",
    icon: "sky-swing",
    iconKey: "sky-swing",
    tags: ["도전형", "모험", "성취", "야외체험"],
    targetAudience: "초등 고학년, 청소년기관",
    targetGrades: ["초등 고학년", "청소년기관"],
    duration: "1교시 체험형 / 2교시 확장형",
    locationType: "야외 체험 공간, 학교 행사장",
    recommendedFor: [
      "학생들의 자신감 향상 활동이 필요한 학교",
      "도전형 야외체험 프로그램을 찾는 기관",
      "축제·체험주간 이벤트를 준비하는 담당자",
    ],
    requirements: [
      "장비 설치 가능한 야외 공간",
      "활동 전 신체 상태 확인",
      "대기 동선 확보",
    ],
    processSteps: [
      "사전 안내 및 도전 목표 설정",
      "안전 장비 착용 확인",
      "기본 탑승 체험",
      "응용 미션 진행",
      "도전 소감 나누기",
    ],
    safetyNotes: [
      "강사 주도하에 순차 탑승으로 운영합니다.",
      "안전 구역과 대기 구역을 분리합니다.",
      "학생별 참여 속도를 고려해 무리하지 않도록 안내합니다.",
    ],
    expectedEffects: [
      "도전 과제에 대한 긍정적 태도 형성",
      "성취 경험을 통한 자존감 향상",
      "친구 응원과 배려 중심의 관계 형성",
    ],
    basePrice: 10000,
    priceNote: "운영 형태와 인원에 따라 견적 안내",
    imageUrl: ASSET_PATHS.programs["sky-swing"],
    imageAlt: "하늘그네 체험에 참여한 학생",
    fallbackGradient: PROGRAM_FALLBACK_GRADIENTS["sky-swing"],
    isPublished: true,
    sortOrder: 2,
  },
  {
    id: "program-003",
    title: "스포츠 클라이밍",
    slug: "sports-climbing",
    shortDescription:
      "균형감각, 집중력, 도전정신을 기르는 신체활동형 체험학습",
    description:
      "클라이밍의 기본 동작을 통해 신체 조절 능력과 집중력을 강화하는 체험형 프로그램입니다. 수준별 코스로 성취 경험을 균형 있게 제공합니다.",
    category: "sports",
    icon: "sports-climbing",
    iconKey: "sports-climbing",
    tags: ["스포츠", "도전", "집중력", "성취감"],
    targetAudience: "초등 3~6학년, 중학생",
    targetGrades: ["초등 3~6학년", "중학생"],
    duration: "1교시 기본 / 2교시 팀 챌린지",
    locationType: "실내 체육관, 이동식 클라이밍 설치 공간",
    recommendedFor: [
      "신체활동 중심 체험수업을 준비하는 학교",
      "집중력 향상 프로그램이 필요한 학급",
      "협동형 스포츠 활동을 원하는 기관",
    ],
    requirements: ["기본 체육 복장", "신발 고정이 가능한 운동화", "체험 동선 확보"],
    processSteps: [
      "기본 자세 및 안전수칙 학습",
      "난이도별 구간 체험",
      "개인 도전 미션",
      "팀 응원 챌린지",
      "성취 리뷰 및 마무리",
    ],
    safetyNotes: [
      "강사의 단계별 안내 후 체험을 시작합니다.",
      "대기 학생은 안전선 밖에서 참여하도록 안내합니다.",
      "체험 전후 컨디션을 점검해 무리한 진행을 방지합니다.",
    ],
    expectedEffects: [
      "균형감각과 집중력 강화",
      "실패를 다시 도전으로 바꾸는 회복탄력성 향상",
      "응원과 협력 중심의 스포츠 태도 형성",
    ],
    basePrice: 10000,
    priceNote: "운영 형태와 인원에 따라 견적 안내",
    imageUrl: ASSET_PATHS.programs["sports-climbing"],
    imageAlt: "스포츠 클라이밍을 체험하는 학생",
    fallbackGradient: PROGRAM_FALLBACK_GRADIENTS["sports-climbing"],
    isPublished: true,
    sortOrder: 3,
  },
  {
    id: "program-004",
    title: "명랑운동회",
    slug: "sports-day",
    shortDescription:
      "협동과 웃음, 경쟁이 함께하는 학교 맞춤형 단체 레크리에이션 프로그램",
    description:
      "학급·학년 단위로 함께 참여할 수 있는 단체 레크리에이션 프로그램입니다. 참여형 게임 중심으로 활기찬 학교 분위기와 소통 경험을 만듭니다.",
    category: "recreation",
    icon: "sports-day",
    iconKey: "sports-day",
    tags: ["단체활동", "협동", "레크리에이션", "학교행사"],
    targetAudience: "초등학교, 중학교, 기관 행사",
    targetGrades: ["초등학교", "중학교", "기관 행사"],
    duration: "1~2교시 / 행사형 반일 운영 가능",
    locationType: "운동장, 강당, 다목적홀",
    recommendedFor: [
      "학교 행사일 프로그램이 필요한 담당자",
      "학년 단위 협동활동을 기획하는 학교",
      "기관 단체 이벤트를 준비하는 운영팀",
    ],
    requirements: ["팀 편성 정보", "간단한 음향 장비", "활동 동선 안내"],
    processSteps: [
      "행사 오리엔테이션",
      "아이스브레이킹 게임",
      "팀별 협동 레이스",
      "학급 맞춤 레크리에이션",
      "시상 및 피드백",
    ],
    safetyNotes: [
      "과열 경쟁보다 협동 중심으로 진행합니다.",
      "현장 상황에 따라 활동 강도를 조정합니다.",
      "사전 안내를 통해 학생 간 배려 문화를 강조합니다.",
    ],
    expectedEffects: [
      "학급 소속감과 협력 경험 강화",
      "신체활동 기반 스트레스 해소",
      "행사 참여 만족도와 즐거운 학교 기억 형성",
    ],
    basePrice: 10000,
    priceNote: "운영 형태와 인원에 따라 견적 안내",
    imageUrl: ASSET_PATHS.programs["sports-day"],
    imageAlt: "명랑운동회 팀 활동 중인 학생들",
    fallbackGradient: PROGRAM_FALLBACK_GRADIENTS["sports-day"],
    isPublished: true,
    sortOrder: 4,
  },
  {
    id: "program-005",
    title: "AI로 만드는 나만의 홈페이지",
    slug: "ai-homepage",
    shortDescription:
      "학생들이 AI를 활용해 자기소개, 관심사, 꿈, 활동 기록을 담은 나만의 홈페이지를 만들어보는 창의형 디지털 체험 프로그램",
    description:
      "AI를 활용해 학생 각자의 이야기와 아이디어를 웹페이지 형태로 구성하는 디지털 창작 프로그램입니다. 기획, 표현, 발표 경험을 함께 제공합니다.",
    category: "ai-creative",
    icon: "ai-homepage",
    iconKey: "ai-homepage",
    tags: ["AI교육", "자기표현", "디지털창작", "포트폴리오"],
    targetAudience: "초등 5~6학년, 중학생, 고등학생",
    targetGrades: ["초등 5~6학년", "중학생", "고등학생"],
    duration: "2교시 기본 / 4교시 프로젝트형",
    locationType: "컴퓨터실, 태블릿 학습 환경",
    recommendedFor: [
      "디지털 창작형 진로체험을 운영하려는 학교",
      "학생 발표 중심 활동을 강화하려는 학급",
      "AI를 활용한 자기표현 수업이 필요한 기관",
    ],
    requirements: ["컴퓨터 또는 태블릿", "인터넷 연결 환경", "기본 타이핑 가능"],
    processSteps: [
      "내 페이지 주제 정하기",
      "콘텐츠 구조 설계",
      "AI 보조를 활용한 문구·이미지 기획",
      "홈페이지 화면 구성",
      "발표 및 피드백",
    ],
    safetyNotes: [
      "개인정보 입력 금지 원칙을 사전 안내합니다.",
      "학생 창작물을 존중하는 피드백 문화로 운영합니다.",
      "공유 범위를 교내 기준에 맞춰 조정합니다.",
    ],
    expectedEffects: [
      "자기이해와 자기표현 역량 강화",
      "AI 활용 문해력과 디지털 제작 경험 확대",
      "발표 기반 의사소통 능력 향상",
    ],
    basePrice: 10000,
    priceNote: "운영 형태와 인원에 따라 견적 안내",
    imageUrl: ASSET_PATHS.programs["ai-homepage"],
    imageAlt: "AI 홈페이지 제작 활동을 진행하는 학생",
    fallbackGradient: PROGRAM_FALLBACK_GRADIENTS["ai-homepage"],
    isPublished: true,
    sortOrder: 5,
  },
  {
    id: "program-006",
    title: "AI로 만드는 나만의 그림일기",
    slug: "ai-diary",
    shortDescription:
      "학생들이 오늘 하루 있었던 일이나 상상 속 이야기를 일기처럼 작성한 뒤, 그 내용을 AI 이미지 프롬프트로 바꾸어 만화 같은 그림일기 결과물로 완성하는 창의 글쓰기 프로그램",
    description:
      "학생들이 자신이 오늘 하루 겪은 일, 기억에 남는 순간, 체험학습에서 느낀 점, 상상 속 하루 등을 짧은 일기 형식으로 작성합니다. 이후 일기 내용을 장면·인물·감정·배경·분위기로 정리해 AI 이미지 생성 프롬프트로 전환하고, 만화 같은 그림일기 결과물로 완성합니다.",
    category: "ai-creative",
    icon: "ai-diary",
    iconKey: "ai-diary",
    tags: [
      "AI창의교육",
      "그림일기",
      "글쓰기",
      "만화이미지",
      "상상력",
      "초등추천",
    ],
    targetAudience: "초등 3~6학년",
    targetGrades: ["초등 3~6학년"],
    duration: "1~2교시 기본 체험형 / 4교시 완성형",
    locationType: "컴퓨터실, 교실 내 디지털 학습 환경",
    recommendedFor: [
      "글쓰기와 창의표현을 함께 강화하고 싶은 학교",
      "AI 기초 경험을 안전하게 시작하려는 학급",
      "결과물 중심 체험수업을 원하는 기관",
    ],
    requirements: [
      "컴퓨터와 인터넷 환경이 있으면 진행 가능",
      "학생 개인 계정이 없어도 수업 설계 가능",
      "강사 계정 또는 운영 계정을 활용한 이미지 생성 운영 가능",
      "실명, 전화번호, 주소, 실제 얼굴 사진 등 민감정보는 사용하지 않도록 사전 안내",
      "학생 본인을 직접 묘사하기보다 캐릭터형 주인공, 상상 속 인물, 만화풍 장면으로 표현",
    ],
    processSteps: [
      "1단계: 오늘 있었던 일 또는 상상 속 하루를 짧게 적기",
      "2단계: 일기 내용을 장면, 등장인물, 감정, 배경, 분위기로 나누어 정리하기",
      "3단계: AI 이미지 생성용 프롬프트로 바꾸기",
      "4단계: AI 이미지 생성 결과 확인하기",
      "5단계: 글과 이미지를 합쳐 나만의 그림일기 결과물 만들기",
    ],
    safetyNotes: [
      "1~2교시 과정: 학생들이 직접 일기를 쓰고 프롬프트를 만들어보는 기본 체험형 과정",
      "4교시 과정: 운영 계정을 통해 이미지 생성과 결과물 정리, 프린트 제공까지 가능한 완성형 과정",
      "개인정보 보호를 위해 민감한 신상정보 입력은 사용하지 않도록 지도합니다.",
      "안전한 운영을 위해 사전 안내, 현장 동선 관리, 학생 눈높이에 맞춘 진행 원칙을 적용합니다.",
    ],
    expectedEffects: [
      "일기 쓰기와 글 구조화 능력 향상",
      "AI 프롬프트 설계 기반의 논리적 표현력 강화",
      "글과 이미지를 결합한 창의 산출물 제작 경험 확대",
    ],
    basePrice: 10000,
    priceNote: "운영 형태와 인원에 따라 견적 안내",
    imageUrl: ASSET_PATHS.programs["ai-diary"],
    imageAlt: "AI 그림일기 제작 활동을 하는 학생",
    fallbackGradient: PROGRAM_FALLBACK_GRADIENTS["ai-diary"],
    isPublished: true,
    sortOrder: 6,
  },
];
